#!/bin/zsh

# Find installers and run them iteratively.
#find . -name install | while read installer ; do sh -c "${installer}" ; done

# Vim
./mac_os/install-vim.sh

# Copy neovim setting.
#mkdir -p ~/.config/nvim/
#cp ./mac_os/.config/nvim/init.vim ~/.config/nvim/

# Copy bash profile.
#cp ./mac_os/.bash_profile ~/

# Copy iterm setting.
#cp -rf ./mac_os/com.googlecode.iterm2.plist ~/Library/Preferences/

# oh_my_zsh
./mac_os/install-ohmyzsh.sh

# Setup global git config
git config --global user.email "binarydiver@outlook.com"
git config --global user.signingkey B5A4BC94
git config --global commit.gpgsign true
git config --global user.name "Jason Park"
